--CREATE SCHEMA [dto];

--CREATE TABLE [dto].[User] (
--	[login] [nvarchar] NOT NULL,
--	[password] [nvarchar] NOT NULL,
--	[email] [nvarchar] NOT NULL,
--	[birthdate] [date] NOT NULL,
--	[isAdmin] [bit] NOT NULL,
--	[isEnabled] [bit] NOT NULL,
--	[todoList] [nvarchar],
--	[creator] [nvarchar],
--	CONSTRAINT userKey PRIMARY KEY ( [login] ),
--	CONSTRAINT creatorKey FOREIGN KEY ( [creator] ) REFERENCES [dto].[User] ( [login] )
--);

--CREATE TABLE [dto].[GeoCoordinates]
--(
--	[latitude] [numeric] NOT NULL,
--	[longitude] [numeric] NOT NULL,
--	[order] [numeric] NOT NULL,
--	CONSTRAINT geoCoordinatesKey PRIMARY KEY ([latitude],[longitude])
--);

--CREATE TABLE [dto].[Zoning]
--(
--	[id] [numeric] NOT NULL IDENTITY(0,1),
--	[name] [nvarchar] NOT NULL,
--	CONSTRAINT zoningKey PRIMARY KEY ([id])
--);

--CREATE TABLE [dto].[Road]
--(
--	[id] [numeric] NOT NULL IDENTITY(0,1),
--	[isPracticable] [bit] NOT NULL,
--	[zoning_id] [numeric] NOT NULL,
--	CONSTRAINT roadKey PRIMARY KEY ([id]),
--	CONSTRAINT roadZoning FOREIGN KEY ([zoning_id]) REFERENCES [dto].[Zoning]([id])
--);

--CREATE TABLE [dto].[RoadGeoreference]
--(
--	[latitude] [numeric] NOT NULL,
--	[longitude][numeric] NOT NULL,
--	[road_id] [numeric] NOT NULL,
--	CONSTRAINT roadGeoreferenceKey PRIMARY KEY ([latitude],[longitude],[road_id]),
--	CONSTRAINT roadRoadGeoreference FOREIGN KEY ([road_id]) REFERENCES [dto].[Road] ([id])
--);

--CREATE TABLE [dto].[Address]
--(
--	[id] [numeric] NOT NULL IDENTITY(0,1),
--	[number] [numeric] NOT NULL,
--	--[postalBox] [char] NOT NULL,
--	[zipCode] [numeric] NOT NULL,
--	--?[city] [nvarchar] NOT NULL,
--	[address] [nvarchar] NOT NULL,
--	[floorNumber] [numeric],
--	[road_id] [numeric] NOT NULL,
--	CONSTRAINT addressKey PRIMARY KEY ([id]),
--	CONSTRAINT addressRoad FOREIGN KEY ([road_id]) REFERENCES [dto].[Road] ([id])
--);

--CREATE TABLE [dto].[Company]
--(
--	[id] [numeric] NOT NULL IDENTITY(0,1),
--	[name] [nvarchar] NOT NULL,
--	--[imageURL] [nvarchar] NOT NULL,
--	-- Change description into sector?
--	[description] [nvarchar],
--	[urlSite] [nvarchar],
--	[status] [nvarchar] NOT NULL,
--	--What's this?[DBGeography] [char] NOT NULL,
--	CONSTRAINT companyKey PRIMARY KEY ([id])
--);

--CREATE TABLE [dto].[History]
--(
--	[id] [numeric] NOT NULL IDENTITY(0,1),
--	[address_id] [numeric] NOT NULL,
--	[startDate] [date] NOT NULL,
--	[endDate] [date],
--	[company_id] [numeric] NOT NULL,
--	CONSTRAINT historyKey PRIMARY KEY ([id]),
--	CONSTRAINT historyAddress FOREIGN KEY ([address_id]) REFERENCES [dto].[Address] ([id]),
--	CONSTRAINT historyCompany FOREIGN KEY ([company_id]) REFERENCES [dto].[Company] ([id])
--);

--CREATE TABLE [dto].[Language]
--(
--	[id] [numeric] NOT NULL IDENTITY(0,1),
--	[name] [nvarchar] NOT NULL,
--	CONSTRAINT languageKey PRIMARY KEY ([id])
--);

--CREATE TABLE [dto].[AddressTranslation]
--(
--	[id] [numeric] NOT NULL IDENTITY(0,1),
--	[address_id] [numeric] NOT NULL,
--	[city] [nvarchar] NOT NULL,
--	CONSTRAINT addressTranslationKey PRIMARY KEY ([id]),
--	CONSTRAINT addressTransleted FOREIGN KEY ([address_id]) REFERENCES [dto].[Address] ([id])
--);

--CREATE TABLE [dto].[CompanyTranslation]
--(
--	[id] [numeric] NOT NULL IDENTITY(0,1),
--	[company_id] [numeric] NOT NULL,
--	[activitySector] [nvarchar] NOT NULL,
--	CONSTRAINT companyTranslationKey PRIMARY KEY ([id]),
--	CONSTRAINT companyTranslated FOREIGN KEY ([company_id]) REFERENCES [dto].[Company] ([id])
--);

--CREATE TABLE [dto].[Creation]
--(
--	[id] [numeric] NOT NULL IDENTITY(0,1),
--	[creationDate] [date] NOT NULL,
--	[user_id] [nvarchar] NOT NULL,
--	[company_id] [numeric] NOT NULL,
--	CONSTRAINT creationKey PRIMARY KEY ([id]),
--	CONSTRAINT creationUser FOREIGN KEY ([user_id]) REFERENCES [dto].[User] ([login]),
--	CONSTRAINT creationCompany FOREIGN KEY ([company_id]) REFERENCES [dto].[Company] ([id])
--);

--CREATE TABLE [dto].[Audit]
--(
--	[id] [numeric] NOT NULL IDENTITY(0,1),
--	[editDate] [date] NOT NULL,
--	[user_id] [nvarchar] NOT NULL,
--	[company_id] [numeric] NOT NULL, 
--	CONSTRAINT auditKey PRIMARY KEY ([id]),
--	CONSTRAINT auditUser FOREIGN KEY ([user_id]) REFERENCES [dto].[User] ([login]),
--	CONSTRAINT auditCompany FOREIGN KEY ([company_id]) REFERENCES [dto].[Company] ([id])
--);